### ISSUE TITLE
请问ubuntu和debain系统的npu是不是都不能用啊

### ISSUE THREAD

**Issue by acai66** [friendlyarm/friendlywrt_device_rk3568#1]
试了几个版本的系统了，rknpu例程跑不起来，dmesg里显示failed to find power_model node.

**Comment by friendlyarm** [comment]
这个日志应该是没影响的。
关于rknn建议查看以下仓库:
https://github.com/rockchip-linux/rknn-toolkit2

**Comment by acai66** [comment]
又在网盘里发布的新版debian下测试了一遍，npu确实可用，感谢
